# -*- coding: utf-8 -*-
"""edit3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13-f3wiXvEFo5be--AegiXuudCaiT_45p
"""

!apt-get install -y -qq glpk-utils
!pip install pyomo

import pyomo.environ as pyo
import numpy as np
from scipy.stats import norm
import pandas as pd

# ۱. پارامترهای مدل (دقیقاً بر اساس مقادیر ارسالی شما)
warehouse_data = {
    'alpha': 0.95,
    'h_p': 0.8,
    'e_i': 1.2,
    'st_mu': 20, 'st_sigma': 4,
    'ret_mu': 12, 'ret_sigma': 2,
    'V_cap': 50, # ظرفیت وسیله نقلیه (فرض بر اساس مقادیر متعارف)
    'techs': {
        1: {'Cp': 200, 'WTech': 2.0, 'LTech': 1.5, 'B': 0.8, 'NV': 10},
        2: {'Cp': 350, 'WTech': 1.5, 'LTech': 1.2, 'B': 0.85, 'NV': 15},
        3: {'Cp': 500, 'WTech': 1.2, 'LTech': 1.0, 'B': 0.9, 'NV': 20},
    }
}

def solve_refined_bilevel(xp_allocation, mode="chance"):
    D = warehouse_data
    model = pyo.ConcreteModel()
    Z = norm.ppf(D['alpha']) if mode == "chance" else 0

    K, I, T, P = range(1, 4), range(0, 5), range(1, 3), range(1, 4)

    # --- لایه رهبر (Leader Parameters) ---
    model.xp = pyo.Param(P, initialize={i+1: xp_allocation[i] for i in range(len(xp_allocation))})

    # [فرمول ۳-۳۰]: محاسبه ظرفیت فیزیکی بر اساس تخصیص فضا (xp)
    cap_p = {p: D['techs'][p]['NV'] * (model.xp[p] / (D['techs'][p]['WTech'] * D['techs'][p]['LTech'])) * D['techs'][p]['B'] for p in P}
    model.Capacity = pyo.Param(P, initialize=cap_p)

    # --- متغیرهای تصمیم (Decision Variables) ---
    model.y = pyo.Var(K, I, T, domain=pyo.Binary)          # [فرمول ۳-۳۳]: متغیر تخصیص کالا
    model.rout = pyo.Var(I, I, T, domain=pyo.Binary)       # [فرمول ۳-۴۵]: متغیر مسیریابی
    model.q = pyo.Var(I, K, T, domain=pyo.NonNegativeReals) # [متغیر q]: موجودی در هر گره/مکان
    model.inv_total = pyo.Var(K, T, domain=pyo.NonNegativeReals) # [متغیر Inv]: موجودی کل کالا
    model.u = pyo.Var(I, T, domain=pyo.NonNegativeReals)    # [فرمول ۳-۴۸]: متغیر کمکی حذف زیرتور

    # --- محاسبات و متغیرهای احتمالی ---
    st_val = D['st_mu'] + Z * D['st_sigma']
    ret_val = D['ret_mu'] + Z * D['ret_sigma']
    model.st_kt = pyo.Var(K, T, domain=pyo.NonNegativeReals)
    model.ret_kt = pyo.Var(K, T, domain=pyo.NonNegativeReals)

    # [فرمول ۳-۳۹]: محدودیت مقدار احتمالی ورود کالا (بزرگتر مساوی)
    model.C3_39 = pyo.Constraint(K, T, rule=lambda m, k, t: m.st_kt[k, t] >= st_val)

    # [فرمول ۳-۴۰]: محدودیت مقدار احتمالی خروج کالا (بزرگتر مساوی)
    model.C3_40 = pyo.Constraint(K, T, rule=lambda m, k, t: m.ret_kt[k, t] >= ret_val)

    # [فرمول ۳-۳۱]: تابع هدف پیرو (هزینه عملیاتی)
    def obj_rule(m):
        return sum(25 * m.rout[i,j,t] for i in I for j in I for t in T) + \
               sum(D['h_p'] * m.inv_total[k,t] for k in K for t in T)
    model.Obj = pyo.Objective(rule=obj_rule, sense=pyo.minimize)

    # --- محدودیت‌های مدل ---

    # [فرمول ۳-۲۹]: محدودیت تعداد کل وسایل نقلیه (بزرگتر مساوی ۱ یا سقف ظرفیت NV)
    total_nv = sum(D['techs'][p]['NV'] for p in P)
    model.C3_29 = pyo.Constraint(T, rule=lambda m, t: sum(m.rout[0, j, t] for j in I if j != 0) <= total_nv)

    # [فرمول ۳-۳۲]: محدودیت کل فضای اشغالی انبار
    model.C3_32 = pyo.Constraint(T, rule=lambda m, t: sum(D['e_i'] * m.inv_total[k,t] for k in K) <= sum(m.xp[p] for p in P))

    # [فرمول ۳-۳۳]: تخصیص هر کالا حداقل به یک مکان فیزیکی
    model.C3_33 = pyo.Constraint(K, T, rule=lambda m, k, t: sum(m.y[k, i, t] for i in I if i != 0) >= 1)

    # [فرمول ۳-۳۴ الی ۳-۳۸]: محدودیت ظرفیت وسیله نقلیه در هر گره (ارتباط q و rout)
    model.C3_34_38 = pyo.Constraint(I, T, rule=lambda m, i, t: sum(m.q[i, k, t] for k in K) <= D['V_cap'] * sum(m.rout[j, i, t] for j in I if i != j) if i != 0 else pyo.Constraint.Skip)

    # [فرمول ۳-۴۱ و ۳-۴۲]: تراز موجودی دوره اول و دوره‌های بعد (استفاده از متغیرهای ۳-۳۹ و ۳-۴۰)
    def inv_bal_rule(m, k, t):
        if t == 1:
            return m.inv_total[k, t] >= m.st_kt[k, t] - m.ret_kt[k, t]
        return m.inv_total[k, t] >= m.inv_total[k, t-1] + m.st_kt[k, t] - m.ret_kt[k, t]
    model.C3_41_42 = pyo.Constraint(K, T, rule=inv_bal_rule)

    # [فرمول ۳-۴۳]: مجموع موجودی در مکان‌ها برابر با موجودی کل کالا (ارتباط q و Inv)
    model.C3_43 = pyo.Constraint(K, T, rule=lambda m, k, t: m.inv_total[k, t] == sum(m.q[i, k, t] for i in I if i != 0))

    # [فرمول ۳-۴۴]: محدودیت ظرفیت کل انبار (کنترل شده توسط Capacity لایه رهبر)
    model.C3_44 = pyo.Constraint(T, rule=lambda m, t: sum(m.inv_total[k,t] for k in K) <= sum(m.Capacity[p] for p in P))

    # [فرمول ۳-۴۵]: مجموع جریان ورودی به هر گره
    model.C3_45 = pyo.Constraint(I, T, rule=lambda m, j, t: sum(m.rout[i, j, t] for i in I if i != j) == sum(m.y[k, j, t] for k in K) if j != 0 else pyo.Constraint.Skip)

    # [فرمول ۳-۴۶]: مجموع جریان خروجی از هر گره
    model.C3_46 = pyo.Constraint(I, T, rule=lambda m, j, t: sum(m.rout[j, i, t] for i in I if i != j) == sum(m.y[k, j, t] for k in K) if j != 0 else pyo.Constraint.Skip)

    # [فرمول ۳-۴۷]: تعادل جریان ورودی و خروجی در هر گره
    model.C3_47 = pyo.Constraint(I, T, rule=lambda m, j, t: sum(m.rout[i, j, t] for i in I if i != j) == sum(m.rout[j, i, t] for i in I if i != j) if j != 0 else pyo.Constraint.Skip)

    # [فرمول ۳-۴۸]: تعیین کران پایین و بالا برای متغیر u (حذف زیرتور)
    model.C3_48 = pyo.Constraint(I, T, rule=lambda m, i, t: (1, m.u[i, t], len(I) - 1) if i != 0 else pyo.Constraint.Skip)

    # [فرمول ۳-۴۹]: محدودیت حذف زیرتور به روش MTZ
    model.C3_49 = pyo.Constraint(I, I, T, rule=lambda m, i, j, t: m.u[i, t] - m.u[j, t] + len(I) * m.rout[i, j, t] <= len(I) - 1 if i != 0 and j != 0 and i != j else pyo.Constraint.Skip)

    # [فرمول ۳-۵۰]: الزام شروع و پایان مسیر از دپو (مبدا مرکزی)
    model.C3_50 = pyo.Constraint(T, rule=lambda m, t: sum(m.rout[0, j, t] for j in I if j != 0) == 1)

    # --- حل مدل و خروجی ---
    # --- ۷. حل و محاسبه فرمول ۳-۲۸ (هزینه کل رهبر) ---
    # --- ۷. بخش حل مدل و محاسبه فرمول نهایی (۳-۲۸) ---
    try:
        # تنظیم حل‌گر GLPK برای محیط گوگل کولب
        solver = pyo.SolverFactory('glpk', executable='/usr/bin/glpsol')
        res = solver.solve(model)

        # بررسی وضعیت بهینگی مدل
        if res.solver.termination_condition == pyo.TerminationCondition.optimal:

            # [فرمول ۳-۲۸]: محاسبه تابع هدف لایه رهبر
            # این فرمول شامل مجموع هزینه‌های سرمایه‌ای (تکنولوژی) + هزینه‌های عملیاتی پیرو (Objective پیرو) است
            leader_fix_cost = sum(D['techs'][p]['Cp'] * (pyo.value(model.xp[p])/(D['techs'][p]['WTech']*D['techs'][p]['LTech'])) * D['techs'][p]['B'] for p in P)

            total_z = pyo.value(model.Obj) + leader_fix_cost

            # خروجی: مقدار هزینه کل (Z) و مجموع موجودی انبار
            return total_z, pyo.value(sum(model.inv_total[k,t] for k in K for t in T))

        else:
            print("Warning: Solver could not find an optimal solution.")
            return None, "Infeasible"

    except Exception as e:
        print(f"Error during optimization: {e}")
        return None, str(e)
if __name__ == "__main__":
    xp_test = [450, 300, 250]
    c, i = solve_refined_bilevel(xp_test)
    print(f"Results with refined formulas - Cost: {c:,.2f}, Inv: {i:,.2f}")